"""initial schema — baseline matching actual SQLAlchemy models

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-04-18 00:00:00.000000

NOTE: This migration is the authoritative baseline.
      All table names, column names and constraints match the
      SQLAlchemy model classes under app/infrastructure/persistence/models/.
      Do NOT edit this file; generate follow-up migrations with:
          python manage.py db migrate -m "description"
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ----------------------------------------------------------
    # 1. users
    # ----------------------------------------------------------
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(100), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('password', sa.String(255), nullable=False),
        sa.Column('role', sa.Enum('admin', 'user', 'guest', name='user_role'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.create_index('idx_user_email',  'users', ['email'],     unique=False)
    op.create_index('idx_user_role',   'users', ['role'],      unique=False)
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)

    # ----------------------------------------------------------
    # 2. rooms  (FK → users)
    # ----------------------------------------------------------
    op.create_table(
        'rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('polygon_data', sa.Text(), nullable=False),
        sa.Column('color', sa.String(80), nullable=False),
        sa.Column('floorplan_url', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_room_name',    'rooms', ['name'],       unique=False)
    op.create_index('idx_room_created', 'rooms', ['created_at'], unique=False)
    op.create_index('idx_room_user',    'rooms', ['user_id'],    unique=False)

    # ----------------------------------------------------------
    # 3. device  (FK → users, rooms)
    # ----------------------------------------------------------
    op.create_table(
        'device',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('code', sa.String(50), nullable=False),
        sa.Column('icon', sa.String(50), nullable=False),
        sa.Column('control_types', sa.Text(), nullable=False),
        sa.Column('device_type', sa.String(50), nullable=True),
        sa.Column('metadata_json', sa.JSON, nullable=False, server_default='{}'),
        sa.Column('category', sa.Enum(
            'sensor', 'actuator', 'light', 'fan', 'ac', 'camera',
            'lock', 'switch', 'tv', 'speaker', 'other',
            name='device_category',
        ), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=True),
        sa.Column('map_x', sa.Float(), nullable=True),
        sa.Column('map_y', sa.Float(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['room_id'],  ['rooms.id'],  ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'],  ['users.id'],  ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', 'user_id', name='uq_device_code_user'),
    )
    op.create_index('idx_device_code',     'device', ['code'],       unique=False)
    op.create_index('idx_device_category', 'device', ['category'],   unique=False)
    op.create_index('idx_device_room',     'device', ['room_id'],    unique=False)
    op.create_index('idx_device_deleted',  'device', ['is_deleted'], unique=False)
    op.create_index('idx_device_user',     'device', ['user_id'],    unique=False)

    # ----------------------------------------------------------
    # 4. device_status  (FK → device, 1-to-1)
    # ----------------------------------------------------------
    op.create_table(
        'device_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_on', sa.Boolean(), nullable=True),
        sa.Column('value', sa.String(50), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['device.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('device_id'),
    )

    # ----------------------------------------------------------
    # 5. control_log  (FK → device, users)
    # ----------------------------------------------------------
    op.create_table(
        'control_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_code', sa.String(50), nullable=True),
        sa.Column('device_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(255), nullable=False),
        sa.Column('source', sa.String(50), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'],   ['users.id'],  ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_device_created',  'control_log', ['device_id', 'created_at'], unique=False)
    op.create_index('idx_source_created',  'control_log', ['source', 'created_at'],    unique=False)
    op.create_index('idx_control_log_dev', 'control_log', ['device_code'],             unique=False)
    op.create_index('idx_control_log_src', 'control_log', ['source'],                  unique=False)
    op.create_index('idx_control_log_uid', 'control_log', ['user_id'],                 unique=False)
    op.create_index('idx_control_log_ts',  'control_log', ['created_at'],              unique=False)

    # ----------------------------------------------------------
    # 6. sensor_data  (FK → device)
    # ----------------------------------------------------------
    op.create_table(
        'sensor_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['device.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_sensor_device_time', 'sensor_data', ['device_id', 'created_at'], unique=False)

    # ----------------------------------------------------------
    # 7. alerts  (FK → users, device)
    # ----------------------------------------------------------
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('device_id', sa.Integer(), nullable=True),
        sa.Column('device_code', sa.String(50), nullable=False),
        sa.Column('message', sa.String(255), nullable=False),
        sa.Column('level', sa.Enum('info', 'warning', 'critical', name='alert_level'), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'],   ['users.id'],  ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_alert_device',    'alerts', ['device_id'],             unique=False)
    op.create_index('idx_alert_read_time', 'alerts', ['is_read', 'created_at'], unique=False)
    op.create_index('idx_alert_created',   'alerts', ['created_at'],            unique=False)
    op.create_index('idx_alert_user',      'alerts', ['user_id'],               unique=False)

    # ----------------------------------------------------------
    # 8. alert_rules  (FK → users, device)
    # ----------------------------------------------------------
    op.create_table(
        'alert_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('sensor_type', sa.String(50), nullable=False),
        sa.Column('min_value', sa.Float(), nullable=True),
        sa.Column('max_value', sa.Float(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'],   ['users.id'],  ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_rule_device_sensor_active', 'alert_rules', ['device_id', 'sensor_type', 'is_active'], unique=False)
    op.create_index('idx_rule_created', 'alert_rules', ['created_at'], unique=False)
    op.create_index('idx_rule_user',    'alert_rules', ['user_id'],    unique=False)

    # ----------------------------------------------------------
    # 9. automations  (FK → device x2)
    # ----------------------------------------------------------
    op.create_table(
        'automations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('trigger_device_id', sa.Integer(), nullable=False),
        sa.Column('trigger_condition', sa.String(255), nullable=False),
        sa.Column('action_device_id', sa.Integer(), nullable=False),
        sa.Column('action_payload', sa.String(255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['action_device_id'],  ['device.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['trigger_device_id'], ['device.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_automation_trigger', 'automations', ['trigger_device_id'], unique=False)
    op.create_index('idx_automation_action',  'automations', ['action_device_id'],  unique=False)
    op.create_index('idx_automation_active',  'automations', ['is_active'],         unique=False)

    # ----------------------------------------------------------
    # 10. schedules  (FK → device, users)
    # ----------------------------------------------------------
    op.create_table(
        'schedules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(255), nullable=False),
        sa.Column('cron_expr', sa.String(100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'],  ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['device_id'],  ['device.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_schedule_device',  'schedules', ['device_id'],  unique=False)
    op.create_index('idx_schedule_active',  'schedules', ['is_active'],  unique=False)
    op.create_index('idx_schedule_creator', 'schedules', ['created_by'], unique=False)

    # ----------------------------------------------------------
    # 11. medicine_reminders  (FK → users)
    # ----------------------------------------------------------
    op.create_table(
        'medicine_reminders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('medicine_name', sa.String(60), nullable=False),
        sa.Column('dosage', sa.String(80), nullable=False),
        sa.Column('time_of_day', sa.String(5), nullable=False),
        sa.Column('recurrence', sa.Enum('daily', 'weekday', 'weekend', name='med_recurrence'), nullable=False),
        sa.Column('notify_email', sa.String(255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_sent_on', sa.Date(), nullable=True),
        sa.Column('last_taken_on', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_med_reminder_user', 'medicine_reminders', ['user_id'],                unique=False)
    op.create_index('idx_med_reminder_time', 'medicine_reminders', ['is_active', 'time_of_day'], unique=False)

    # ----------------------------------------------------------
    # 12. alert_saved_view_configs  (FK → users, 1-to-1)
    # ----------------------------------------------------------
    op.create_table(
        'alert_saved_view_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('views_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index('idx_alert_saved_view_user', 'alert_saved_view_configs', ['user_id'], unique=False)

    # ----------------------------------------------------------
    # 13. notifications  (FK → users, alerts)
    # ----------------------------------------------------------
    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('alert_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'],  ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'],  ['users.id'],   ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notif_created',   'notifications', ['created_at'],         unique=False)
    op.create_index('idx_notif_alert',     'notifications', ['alert_id'],           unique=False)

    # ----------------------------------------------------------
    # 14. patient_profiles  (FK → users, 1-to-1)
    # ----------------------------------------------------------
    op.create_table(
        'patient_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('patient_name', sa.String(120), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('gender', sa.String(30), nullable=True),
        sa.Column('baseline_hr_rest', sa.Float(), nullable=True),
        sa.Column('baseline_hr_min',  sa.Float(), nullable=True),
        sa.Column('baseline_hr_max',  sa.Float(), nullable=True),
        sa.Column('diagnosis_notes', sa.Text(), nullable=True),
        sa.Column('medications', sa.Text(), nullable=True),
        sa.Column('consent_analytics',  sa.Boolean(), nullable=False),
        sa.Column('consent_pdf_export', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index('idx_patient_profile_user', 'patient_profiles', ['user_id'], unique=False)

    # ----------------------------------------------------------
    # 15. patient_hr_records  (FK → users)
    # ----------------------------------------------------------
    op.create_table(
        'patient_hr_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('bpm', sa.Integer(), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False),
        sa.Column('risk', sa.String(30), nullable=True),
        sa.Column('mood', sa.String(30), nullable=True),
        sa.Column('source', sa.String(30), nullable=False),
        sa.Column('note', sa.String(255), nullable=True),
        sa.Column('hrv_rmssd',   sa.Float(), nullable=True),
        sa.Column('hrv_sdnn',    sa.Float(), nullable=True),
        sa.Column('hrv_pnn50',   sa.Float(), nullable=True),
        sa.Column('hrv_mean_rr', sa.Float(), nullable=True),
        sa.Column('hrv_risk',    sa.String(30), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.Column('created_at',  sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_patient_hr_user_time', 'patient_hr_records', ['user_id', 'recorded_at'], unique=False)
    op.create_index('idx_patient_hr_severity',  'patient_hr_records', ['severity'],               unique=False)

    # ----------------------------------------------------------
    # 16. password_reset_tokens  (FK → users)
    # ----------------------------------------------------------
    op.create_table(
        'password_reset_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.String(64), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token_hash'),
    )
    op.create_index('idx_password_reset_token_user',   'password_reset_tokens', ['user_id'],   unique=False)
    op.create_index('idx_password_reset_token_expiry', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_token_used',   'password_reset_tokens', ['used_at'],   unique=False)


def downgrade():
    # Drop in reverse FK-dependency order
    op.drop_table('password_reset_tokens')
    op.drop_table('patient_hr_records')
    op.drop_table('patient_profiles')
    op.drop_table('notifications')
    op.drop_table('alert_saved_view_configs')
    op.drop_table('medicine_reminders')
    op.drop_table('schedules')
    op.drop_table('automations')
    op.drop_table('alert_rules')
    op.drop_table('alerts')
    op.drop_table('sensor_data')
    op.drop_table('control_log')
    op.drop_table('device_status')
    op.drop_table('device')
    op.drop_table('rooms')
    op.drop_table('users')
